# 使用官方的Node.js基础镜像作为基础镜像
FROM node:14
# 设置工作目录
WORKDIR /appClient
# 将package.json和package-lock.json复制到工作目录
COPY package*.json ./
# 安装依赖
RUN npm install
# 将tsconfig.json复制到工作目录如果你的项目使用了TypeScript
COPY tsconfig.json ./
# 将src复制到工作目录
COPY ./src /appClient/src
# 如果你的项目使用了Babel转译代码，复制babel.config.js文件
COPY babel.config.js ./
# 如果你对Vue CLI的默认配置做了修改，复制vue.config.js文件
COPY vue.config.js ./
# 将前端项目（通常是dist文件夹）复制到工作目录,记住要提前将vue打包成dist文件夹
COPY dist /appClient/dist
# 暴露端口
EXPOSE 8080
# 运行命令
CMD ["npm", "start"]